name: Update And Reboot Bot On Server
on: [push]
jobs:
  build:
    name: SSH Connection
    runs-on: ubuntu-latest
    steps:
      - name: Command Execution
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /home/minilan/github/WebTech-Discord-Bot
            git pull origin main
            pm2 restart bot
            ip=$(curl -s https://api.ipify.org)
            # Découper l'IP en octets et l'afficher avec des barres obliques
            formatted_ip=$(echo $ip | sed 's/\./\//g')
            echo "Adresse IP publique du runner : $formatted_ip"