name: Discord Bot Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy On Server
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Configure
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy
        run: |
          ssh -t -t -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            cd /home/minilan/github/WebTech-Discord-Bot
            git pull origin main
            npm install --production
            pm2 restart ecosystem.config.js
            exit
          EOF
